version: '3.4'
name: cruddb
networks:
  python_network:
    driver: bridge
    name: python_network
services:
  app:
    build: .
    environment:
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - python_network
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: "passw0rd"
      MYSQL_PASSWORD: "passw0rd"
      MYSQL_DATABASE: "cruddb"
    networks:
      - python_network